### ISSUE TITLE
avi playing error

### ISSUE THREAD

**Issue by Albinzr** [icza/mjpeg#1]
Every time when I try to play the video i'm getting this error
![screen shot 2018-10-02 at 10 38 55 pm](https://user-images.githubusercontent.com/7425577/46364700-31565100-c694-11e8-9a95-59779dd53ace.png)
Can you help me fix this issue?

**Comment by icza** [comment]
Can you post the code how you generate the video?

**Comment by Albinzr** [comment]
@icza sure

`

        func convertBase64ImageToVideo(umbralla Umbralla) {

	     aviWritter, aviWritterError := mjpeg.New(time.Now().String()+".avi", 144, 108, 10)
	     handleError("newAviWritter", aviWritterError)

	     for _, session := range umbralla.ScreenDetails {
		b64image := session.Screen
		currentImageInByte, imageError := base64.StdEncoding.DecodeString(b64image)
		handleError("bas64ImageToBytes[]", imageError)
		aviWritterError : = aviWritter.AddFrame(currentImageInByte)
		handleError("addFrameToAviWritter", aviWritterError)
	}

	   handleError("closeAviWritter", aviWritter.Close())
	   fmt.Println("Converted to video")
     }

     func handleError(errorFrom string, errorDetails error) {
	   if errorDetails != nil {
		fmt.Println(errorFrom, errorDetails)
		return
	  }
     } 

`


Thanks..

**Comment by icza** [comment]
Your code to create the video looks correct. If the created video is corrupt, then the following may be the cause:

- The images (binary data) you add as frames are invalid images (note: they must be JPEG images).
- The size of images is not 144x108 as you indicated at `mjpeg.New()`.
- The video is not closed properly.

Are you getting any errors?

Please try your code with simple jpeg files you create with any drawing application.

**Comment by icza** [comment]
Also please check my example at https://github.com/icza/mjpeg/tree/master/_example

Can you play the video that is the output of that example?

**Comment by Albinzr** [comment]
@icza Im having the same issue with the example,
![screen shot 2018-10-04 at 8 44 02 am](https://user-images.githubusercontent.com/7425577/46450978-c13ded00-c7b1-11e8-84c4-999483637356.png)

**Comment by icza** [comment]
Well, I have no problem playing the generated videos. I've tried them with Totem (Ubuntu default video player) and mplayer, both report no errors.

**Comment by Albinzr** [comment]
@icza  I will check it out and let you know

**Comment by Albinzr** [comment]
@icza I checked in mac and windows its working fine but in mac its not working fine,
[ also is there any direct way to get video in mp4 instead of avi, any pointers on how to do it ? ]
Thanks

**Comment by icza** [comment]
You may use 3rd party tools to convert to other video formats, such as ffmpeg. But if you want to use ffmpeg, you can use it to create the video in the first place.

**Comment by Albinzr** [comment]
@icza  ya I looked in to ffmpeg, but your work felt clean and simple.
Im closing this issue
